### ISSUE TITLE
生成PDF过程中提示RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by rossy0914** [YaoZeyuan/micro_backup#71]
生成PDF的时候频繁报错，log如下：

> 2021-10-08 14:10:42.907: [GenerateCustomer] 正在添加页面2014-06-25(第173/362项)下,第11/11条微博 
2021-10-08 14:10:42.910: [GenerateCustomer] 将页面2014-06-26(第174/362项)添加到pdf文件中 
2021-10-08 14:10:42.910: [GenerateCustomer] 正在添加页面2014-06-26(第174/362项)下,第1/5条微博 
2021-10-08 14:10:42.914: [GenerateCustomer] 正在添加页面2014-06-26(第174/362项)下,第2/5条微博 
2021-10-08 14:10:43.239: [GenerateCustomer] catch error 
2021-10-08 14:10:43.240: [GenerateCustomer] RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:71:11)
    at Buffer.readUInt16LE (internal/buffer.js:230:5)
    at Object.validate (C:\Users\rossy\AppData\Local\Programs\stablog\resources\app\node_modules\image-size\dist\types\cur.js:7:20)
    at finder (C:\Users\rossy\AppData\Local\Programs\stablog\resources\app\node_modules\image-size\dist\detector.js:26:55)
    at Array.find (<anonymous>)
    at Object.detector (C:\Users\rossy\AppData\Local\Programs\stablog\resources\app\node_modules\image-size\dist\detector.js:27:17)
    at lookup (C:\Users\rossy\AppData\Local\Programs\stablog\resources\app\node_modules\image-size\dist\index.js:32:29)
    at Function.imageSize (C:\Users\rossy\AppData\Local\Programs\stablog\resources\app\node_modules\image-size\dist\index.js:87:16)
    at C:\Users\rossy\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:1034:51
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\rossy\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:50:103)
    at _next (C:\Users\rossy\AppData\Local\Programs\stablog\resources\app\dist\command\generate\customer.js:52:194) 
2021-10-08 14:10:43.240: [GenerateCustomer] command finish 
2021-10-08 14:10:43.240: [DispatchCommand] 生成电子书命令执行完毕 
2021-10-08 14:10:43.241: [DispatchCommand] 所有命令执行完毕 
2021-10-08 14:10:43.241: [DispatchCommand] command finish 
2021-10-08 14:10:43.242: 所有任务执行完毕, 打开电子书文件夹 =>   C:\Users\rossy\AppData\Local\Programs\stablog\resources\app\稳部落输出的电子书

**Comment by pandada1999** [comment]
同问题
